### ISSUE TITLE
Feature request: Multiple Twilio numbers

### ISSUE THREAD

**Issue by markh999** [smooch/smooch-core-js#101]
Hi team,

A feature request - we have users all over the world and want to communicate with them using Twilio, however, we're forced to choose one number - so our users in the UK, for example, have to text a US number.

Given that you know the users country code, it'd be awesome if you could update the Twilio integration so we could route to multiple numbers - so that where we have a UK number and a UK user, Smooch uses this, whereas where we have a US number, the US user is used.

We'd then also configure a 'default' number, to use in the event that a local number wasn't available.

Apols if this has already been suggested!

Mark

**Comment by spasiu** [comment]
If we understand correctly, you'd like each Smooch app to integrate to multiple SMS numbers, and then for the Web messenger to connect the user to a number appropriate for their region when the user links to SMS.

This is an interesting feature request, and we've brought it to the product team to take into consideration.

In the meantime, it is currently on our long-term roadmap to support multiple SMS numbers per-app.

Thanks for your interesting feature request!
