### ISSUE TITLE
Is documentation out of sync with the code base?

### ISSUE THREAD

**Issue by hwhelchel** [smooch/smooch-core-js#113]
I'm working on integrating smooch with an app and the smooch-core-js method signatures are different than the documentation. Am I looking at the wrong docs?

https://docs.smooch.io/rest/#get-app-user

For example the library requires one param to get an appUser but the docs say two params are required.

```js
smooch.appUsers.get(userId) // lib
smooch.appUsers.get(appId, userId) // docs
```

**Comment by mspensieri** [comment]
The docs show usage when using `account` scope access, which requires you to specify an app ID for most routes. When using this library with `app` scope, the app ID is implied by your secret key, and is therefore not passed as the first argument when making api calls.

```javascript
var smooch = new SmoochCore({
    keyId: 'app_00000000000',
    secret: 'XXXXXXXXXXX',
    scope: 'app'
});

smooch.appUsers.get(userId)
```

vs

```javascript
var smooch = new SmoochCore({
    keyId: 'act_000000000000000',
    secret: 'YYYYYYYYYYYYYY',
    scope: 'account'
});

smooch.appUsers.get(appId, userId)
```

**Comment by hwhelchel** [comment]
Thanks!
