### ISSUE TITLE
Error on creating appUser

### ISSUE THREAD

**Issue by segpacto** [smooch/smooch-core-js#125]
package:  "smooch-core": "^6.3.0"
Following the instructions to create an appUser (https://docs.smooch.io/rest/#pre-create-app-user)
while :
`apiClient
                    .appUsers.create(appId, {
                        userId: 'steveb@channel5.com',
                        givenName: 'Steve',
                        properties: {
                            favoriteFood: 'prizza'
                        }
                    })`
I am getting "TypeError: userId.trim is not a function" because on the package on 'smooch-core/lib/api/appUsers.js' line #68 is trying to trim.
Is there anything wrong following the instructions of the documentation ?

Thanks

**Comment by spasiu** [comment]
Looks like a bug in the lib... I think trim is being applied to the object because the second argument is expected to be the userId string.

```
apiClient .appUsers.create(appId, 'steveb@channel5.com', { givenName: 'Steve', properties: { favoriteFood: 'prizza' } })
```

^ this call should work.

**Comment by segpacto** [comment]
Thanks for the fast reply,
Yes, that was the solution I applied while using the library, but might be good to update the documentation or fix the Bug.
Thanks in advance again, keep the hard work :+1:

**Comment by alavers** [comment]
Closing now that the docs have since been updated
