### ISSUE TITLE
delete function doesnt exist on appUsers

### ISSUE THREAD

**Issue by segpacto** [smooch/smooch-core-js#126]
package: "smooch-core": "^6.3.0"

Going throw the documentation (https://docs.smooch.io/rest/#delete-app-user) there is described the method delete an app user.
However when try to access to this method it says that doesnt exist, at the same time, going throw your library, precisely on ('smooch-core/src/api/appUsers') I cant find the method delete, I can find others like 'deleteMessage', 'deleteProfile', 'unlinkChannel' but not the one described on the documentation.

**Comment by mspensieri** [comment]
The delete function was added in v6.4.0, can you update to the latest version and try again?

**Comment by segpacto** [comment]
Yes, you were right, thanks for the fast response.
