### ISSUE TITLE
line Integration required fields are not the same as rest API

### ISSUE THREAD

**Issue by Yliu12** [smooch/smooch-core-js#131]
https://github.com/smooch/smooch-core-js/blob/77ddf10d7e4a21293561263a72df04baf193dce9/src/api/integrations.js#L62

This Line here is not consist with the documentation where the required fields are channelId and ChannelSecret 

https://docs.smooch.io/rest/#integration-schemas

![image](https://user-images.githubusercontent.com/5702042/58664185-22e03800-82fc-11e9-9899-c2e77e09a38c.png)

**Comment by Yliu12** [comment]
I modified that line to 
```line: new IntegrationType(['channelId', 'channelSecret'], ['displayName']),```
And the server processed that request just fine.

Please confirm if this is a bug.

**Comment by mspensieri** [comment]
See https://github.com/smooch/smooch-core-js/pull/132#issuecomment-505882872
