### ISSUE TITLE
Typing activity not received

### ISSUE THREAD

**Issue by PierrickI3** [smooch/smooch-core-js#134]
I can successfully send typing activity from AppMaker but I never receive the typing activity in my node.js server even though my webhook is configured to receive `Typing AppUser`.

I tried from FB messenger, WhatsApp and Telegram. But I never receive the event in my `/messages` endpoint.

Has anyone faced the same issue?

**Comment by mspensieri** [comment]
The `Typing AppUser` webhook only triggers for typing events with `role: 'appUser'`. If you are sending a typing activity from the API with `role: 'appMaker'` it will not trigger this webhook.

https://docs.smooch.io/rest/#typing-events

> A `typing:appUser` webhook triggers when an appUser starts or stops typing a response on a supported channel.

According to the [channel capabilities grid](https://docs.smooch.io/guide/channel-capabilities/) none of the channels you mention support typing events from the user. Unfortunately these are limitations of the channels themselves, they don't expose typing events at all (hence the `n/a` in the grid).

**Comment by PierrickI3** [comment]
Thanks for your answer. I was not aware of the channel capabilities grid page.
