### ISSUE TITLE
Support sending images

### ISSUE THREAD

**Issue by skhavari** [smooch/smooch-core-js#30]
As a developer I'd like to use smooch core to send images.  Thanks!

**Comment by lemieux** [comment]
Hey @skhavari, it's actually implemented in smooch core by calling `smooch.conversations.uploadImage(userId, source[, message])` where `source` must be a Blob (or a File) on the client side or a Readable stream on the server side. (https://github.com/smooch/smooch-core-js/blob/integration/src/api/conversations.js#L47)

This just made me realize it was not documented at all... straight to the todo list :)
