### ISSUE TITLE
Package.json gets bundled for the browser

### ISSUE THREAD

**Issue by webyak** [smooch/smooch-core-js#52]
The whole `package.json` is getting bundled with webpack just for storing the current version within [`this.VERSION`](https://github.com/smooch/smooch-core-js/blob/integration/src/smooch.js#L12). Is that an unexpected behaviour or is it on purpose?

**Comment by lemieux** [comment]
Hey @webyak, we didn't realize it would bundle the whole file at the time the lib was written. We are aware of this, but we never had time to fix it unfortunately. I'll give it a nudge in our bug tracker.

**Comment by lemieux** [comment]
Closing this as this is no longer a browser library.
