### ISSUE TITLE
Shows only 3 action button in FB Messenger

### ISSUE THREAD

**Issue by devhyunjae** [smooch/smooch-core-js#91]
## Code
```
smooch.appUsers.sendMessage('5963c0d619a30a2e00de36b8', 'c7f6e6d6c3a637261bd9656f', {
    text: 'Just put some vinegar on it',
    role: 'appMaker',
    type: 'text',
    actions: [
      {
        type: 'link',
        text: 'Slot 1',
        uri: 'http://example.com'
      },
      {
        type: 'link',
        text: 'Slot 2',
        uri: 'http://example.com'
      },
      {
        type: 'link',
        text: 'Slot 3',
        uri: 'http://example.com'
      },
      {
        type: 'link',
        text: 'Slot 4',
        uri: 'http://example.com'
      },
      {
        type: 'link',
        text: 'Slot 5',
        uri: 'http://example.com'
      },
    ]
})
```
## In our web(Works fine)
<img width="746" alt="screen shot 2017-07-31 at 2 43 08 pm" src="https://user-images.githubusercontent.com/12890257/28764200-d284a456-75fe-11e7-86c4-4ac88ec0fc90.png">

## In FB Messenger(Shows only 3)
<img width="599" alt="screen shot 2017-07-31 at 2 43 01 pm" src="https://user-images.githubusercontent.com/12890257/28764210-e4d7813c-75fe-11e7-99b1-806c664a2751.png">

**Comment by devhyunjae** [comment]
<img width="769" alt="screen shot 2017-07-31 at 5 19 13 pm" src="https://user-images.githubusercontent.com/12890257/28769167-615fb1b4-7615-11e7-87a6-401840f68e49.png">

Looks like this is FB policy. But still, should be great if you guys update your docs to announce this or make a warning log that the developers can know

**Comment by mspensieri** [comment]
Thanks for the report. We've added a mention in the [Facebook Messenger docs](https://docs.smooch.io/guide/facebook-messenger/#action-buttons) about the size restriction
