### ISSUE TITLE
How to originate call to sendMessage as `appMaker` from `Smooch.getCore()`

### ISSUE THREAD

**Issue by zanona** [smooch/smooch-core-js#92]
Hi guys,
How can I original a call to `Smoch.getCore().appUsers.sendMessage(…)` as an appMaker _(this should be done directly from the client running the sdk)_?

Currently the [documentation states](https://docs.smooch.io/rest/?javascript#post-message):

> For messages originating from an app maker, a jwt credential with app level scope must be used.

and an example is provided:

```js
smooch.appUsers.sendMessage('5963c0d619a30a2e00de36b8', 'c7f6e6d6c3a637261bd9656f', {
    type: 'text',
    text: 'Just put some vinegar on it',
    role: 'appMaker'
}).then(() => {
    // async code
});
```

But there's no explanation on how to set the jwt credential for an already instantiated version of `SmoochCore` provided by the `Smooch.getCore()` method.

Thanks

**Comment by mspensieri** [comment]
> How can I original a call to Smoch.getCore().appUsers.sendMessage(…) as an appMaker (this should be done directly from the client running the sdk)?

Sending `appMaker` messages from a client browser is not supported, and strongly discouraged. As you saw in the documentation, a JWT with `app` scope is required to send messages as an app maker. An app scope JWT should *never* be distributed to an end-user - it's intended to be used for server-to-server calls only. JWTs with scope `app` provide access to your entire user base, as well as APIs to configure your app itself. It has permission to:

1. create/modify webhooks for your app
2. manage you app's integrations
3. create new users, modify existing users, fetch conversation history and user profile for your entire userbase
4. and more...

To send a message as an app maker, you should have your own server [instantiate an instance of smooch core](https://github.com/smooch/smooch-core-js#server-side), and send the message with a server-to-server call to Smooch.

**Comment by zanona** [comment]
Thanks Mike.
That makes sense, but it also seems a lot of work to just notify users with
predefined messages based on events isn't it?

Perhaps creating whispers based on events and fire those events via client
then?

Thanks

**Comment by mspensieri** [comment]
> Perhaps creating whispers based on events and fire those events via client
then?

Whispers are actually being deprecated as of October 1st, there was an email blast sent out at the beginning of July with that information. Our [replacement guide](https://docs.smooch.io/guide/whisper-replacements/) outlines some ways your could build that functionality into your own backend, but yes it would require a bit of development effort to make that happen.

**Comment by zanona** [comment]
Thanks Mike.
Didn't know about the deprecation. I appreciate the heads up.
Will have a look on the samples.

All the best
