### ISSUE TITLE
[Messenger Channel] How can I receive facebook user id in clients.raw?

### ISSUE THREAD

**Issue by rgnevashev** [smooch/smooch-core-js#93]

**Comment by mspensieri** [comment]
Raw client info contains metadata about the user, it doesn't contain the identifier of the user itself. 

To know the page-scoped id of the Messenger user, you can use the [GET channels API](https://docs.smooch.io/rest/#get-app-user-channel-entities). I just checked and it looks like `smooch-core` isn't currently wrapping that endpoint. I've filed an internal issue to add support for it

**Comment by mspensieri** [comment]
The `getChannels` endpoint is now exposed in v5.2.0
